/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./../src/layouts/AuthLayout/index.vue')['default']
    Bar: typeof import('./../src/components/Echarts/Bar.vue')['default']
    BaseBreadcrumb: typeof import('./../src/layouts/BaseLayout/components/BaseBreadcrumb.vue')['default']
    BaseContent: typeof import('./../src/layouts/BaseLayout/components/BaseContent.vue')['default']
    BaseFooter: typeof import('./../src/layouts/BaseLayout/components/BaseFooter.vue')['default']
    BaseHeader: typeof import('./../src/layouts/BaseLayout/components/baseHeader.vue')['default']
    BaseLayout: typeof import('./../src/layouts/BaseLayout/index.vue')['default']
    BaseSidebar: typeof import('./../src/layouts/BaseLayout/components/BaseSidebar.vue')['default']
    BaseTabs: typeof import('./../src/layouts/BaseLayout/components/BaseTabs.vue')['default']
    Earth: typeof import('./../src/components/Echarts/Earth.vue')['default']
    LineChart: typeof import('./../src/components/Echarts/LineChart.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Pie: typeof import('./../src/components/Echarts/Pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
